Help document
iberianpig/tig-explorer.vim pull request #19
Opened 2020-06-15 14:20 UTC by kyoh86

This plugin is so convenient.
So I try proposing a document.

2020-06-16 13:22 UTC, iberianpig requested changes
Thanks for creating a pull request.
Could you modify the following sentences?

2020-06-16 13:22 UTC, iberianpig commented on doc/tig-explorer.txt
> +    And you can pass fraze like `:TigGrep (fraze)` to open with the fraze.
```suggestion
    And you can pass PATTERN like `:TigGrep (PATTERN)` to grep with the PATTERN.
```

2020-06-17 01:54 UTC, kyoh86 commented on doc/tig-explorer.txt
> +    And you can pass fraze like `:TigGrep (fraze)` to open with the fraze.
thanks

2020-06-17 01:58 UTC, kyoh86 commented
@iberianpig Thank you for your review.
I fixed words!

2020-06-17 02:20 UTC, merged

2020-06-17 02:22 UTC, iberianpig commented
Thanks for your contribution.👍